# Generated by Django 4.1 on 2022-09-14 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appBlog", "0002_user_imagen_alter_comment_commenter_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="commenter_id",),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appBlog.user",
            ),
        ),
    ]
