# Generated by Django 4.1.1 on 2022-09-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appBlog", "0004_alter_comment_author_delete_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="publication", name="category",),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
                ("publications", models.ManyToManyField(to="appBlog.publication")),
            ],
        ),
    ]
