# Generated by Django 4.1 on 2022-09-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0007_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
