# Generated by Django 4.1 on 2022-09-21 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0008_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appBlog.publication'),
            preserve_default=False,
        ),
    ]
