# Generated by Django 4.1 on 2022-09-29 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appBlog", "0014_alter_publication_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="comment_body", new_name="body",
        ),
        migrations.RemoveField(model_name="comment", name="commenter_name",),
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
