# Generated by Django 4.1 on 2022-10-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0016_alter_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(null=True, upload_to='publications'),
        ),
    ]
